---
- name: Create Stack Builder configuration tasks
  hosts: localhost
  gather_facts: no
  connection: local

  tasks:

    - name: Ensure stage directory exists
      file: path=../../../stage/stack-builder-configs/ state=directory

    - name: Create Stack Builder AMI IDs configuration file
      stack_builder_ami_ids:
        aem_profile: "{{ aem.profile }}"
        os_type: "{{ os_type }}"
        jdk_type: "jdk{{ java.version }}"
        version: "{{ lookup('env','version') }}"
        out_file: "../../../stage/stack-builder-configs/{{ aem.profile }}-{{ os_type }}-jdk{{ java.version }}-stack-builder-ami-ids.yaml"
        region: "{{ aws.region }}"
